# Generated by Django 4.2.4 on 2023-08-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='product_favorits',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
